### ISSUE TITLE
Ensure WeakMaps can't store uncollectable entries

### ISSUE THREAD

**Issue by Jamesernator** [bmeck/proposal-richer-keys#4]
This is probably planned but doesn't seem to be explicitly stated, but currently `WeakMap`s can't store any primitives which means it probably shouldn't be able to store composite keys that only consist of primitives.

e.g. This shouldn't be allowed as it wouldn't be collectable:

```js
const wm = new WeakMap();
const key = compositeKey(1, 2);

// Probably should throw an error just like wm.set(1)
wm.set(key, 'foo');
```

This could be easily accomplished by just stamping the object if it only consists of primitive entries and throw in `.set` (and `WeakSet.prototype.add`) if the object contains that stamp.

**Comment by zloirock** [comment]
In your example, `compositeKey(1, 2)` throws an error because it should contain a non-primitive component.

**Comment by Jamesernator** [comment]
Hmmm maybe I misunderstood what it's relation to `rekey` was, this makes the `rekey` part of the proposal considerably less useful if that's the case as I thought `compositeKey` was just for generating a unique object from any set of keys (primitive or otherwise).
